server:
  port: 9000
  servlet:
    contextPath: /api


spring:
  jpa:
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:mysql://localhost:3307/db_nearme?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: ""