server:
  port: 9000
  servlet:
    contextPath: /api


spring:
  jpa:
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:mysql://localhost:3306/db_nearme
    username: root
    password: ""