package com.hackaton.nearme.services;

import com.hackaton.nearme.model.Coupon;
import com.hackaton.nearme.model.Merchant;
import com.hackaton.nearme.model.Promotion;
import com.hackaton.nearme.repositories.CouponRepository;
import com.hackaton.nearme.repositories.MerchantRepository;
import com.hackaton.nearme.repositories.PromotionRepository;
import com.hackaton.nearme.utils.DateTimeCreation;
import javassist.NotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
public class PromotionService {


    private PromotionRepository promotionRepository;

    private CouponRepository couponRepository;

    private MerchantRepository merchantRepository;

    private DateTimeCreation dateTimeCreation;

    public PromotionService(PromotionRepository promotionRepository, CouponRepository couponRepository, MerchantRepository merchantRepository) {
        this.promotionRepository = promotionRepository;
        this.couponRepository = couponRepository;
        this.merchantRepository = merchantRepository;
        this.dateTimeCreation = new DateTimeCreation();
    }

    public Promotion getPromotionById(int id) throws NotFoundException {
        return promotionRepository.findById(id).orElseThrow(
                () -> new NotFoundException("Not found")
        );

    }

    public List<Promotion> getPromotion() {
        return promotionRepository.findAll();
    }

    public Promotion createPromotion(int merchantId, Promotion promotion) {

        Merchant merchant = merchantRepository.findById(merchantId).get();
        promotion.setMerchant(merchant);
        promotion.setStartAt(dateTimeCreation.getCreatedDate());
        promotion.setExpiresAt(dateTimeCreation.getExpiredDate());
        Promotion newPromotion = promotionRepository.save(promotion);

        for (int i = 0; i < promotion.getQuantity(); i++) {
            couponRepository.save(createCoupon(newPromotion));
        }

        return newPromotion;
    }

    private Coupon createCoupon(Promotion promotion) {
        Coupon coupon = new Coupon();
        coupon.setPromotion(promotion);
        coupon.setCode(UUID.randomUUID().toString().toUpperCase());
        coupon.setCreatedDate(promotion.getStartAt());
        coupon.setExpiredDate(promotion.getExpiresAt());
        coupon.setTitleName(promotion.getTitleName());
        coupon.setDescription(promotion.getDescription());
        coupon.setImagePath(promotion.getImagePath());
        coupon.setMerchantName(promotion.getMerchant().getMerchantName());
        coupon.setQrCode(
                "iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAR50lEQVR4Xu2d4ZUlNxGF5QgMERhHsGwEhkjMRoCJAIhglwiMIwFHsBABkME6Ajg1Zt/svFbd7rpP0vTb+fqc+TNP6pau6nZJt0ulL1pr/233ff22tfb3wV3IMPmxtfab5Fnx/78Z7fhza+1PSb34/x+T31S/A49vjHrKFr4w+uZiYjxqTpXoNATZYgtBtphAkDkcnH5XPMgWYjzIILPDg/SBxIPgQR4QgCAQ5FMEWINc2QMEgSAQREzHIAgEgSA3EMRRLgYtj57cZobcqfrmrEFUv1fLna4EPHq8Vb+VvD3DhtQ906nlngcZDZjbcQhSQw6C1PCCIB288CBjlCrXc+JBaiSWpfEgNTDxIDW88CB4kAsC6iPi6Ck1a5AaUe3SeJAadHiQGl7DPcgvWmuvkjaohb/67T+ttX8n93QJ8q619uvknlnQYRTPgh//0Vr7LrmfwuR1a+1tUk/1uzbMj6WjjdHW3qU8iMIkAjWrl+tBftVa+2qwff2ztfYhuedwgsyQLWdEtVYH9JbyLiarF6uKIKr/zvTLJYh6IbpjpLwqBHFRLdSDIFuwIEjBgPaK4kH2EBrzOx5kiyMeZIxtybvgQfAgFwRcY1AWhgdZwOL/CxDZbkPWIFcIuKEmEKT2tnRfDDMowxSLKdYFgZB4vxxoZT8J+VS9NFS9MNhsL7t6gSnZUvX7L0KiV1KukoAziFmkDzS+GVMs922ZdctN2qDquZKm+zFw9DRK3Q+CQJBD6zIIsjUU94XomhzfQTrI4UFq5uR8DMSDdBC4l0U6BIEgHxHAg+BBLgi4LwY8yAuTeV1DYZFe8zyoWFcI3MsU63ettYgM7V1ZSs8oGwvI3hXRxn9NfovnxPOq9QJLlc40+6j3Q2vtX8nz3ohoWGX6yoNkeEU0coYJKtaYF83DXVxVw82sODoH1EAoLrdyJWC3LaO3IUMQdyQ69SDIFhQIMs7AWKQXscSDbAHDg1xh8pJjsSAIBPmIAOHuHe8CQSAIBBHTLggCQaYRREmaxaXApXh8s8iSJbhJG0J2zTb/Z6c6RYOyuXj0+9ukg3sJKTIpVOHlLtJDAs4SYOw9L/vdScfqqlhK+nbtK/DPMBk+xXIb6dZzCeJ+KMwI4n7/UcGKewarvtdkdV3pW7VlJUFcO3HrQZAichBkCxgE6RjR6Nicop1eiuNBasjhQWp44UFqeKVrEKZYWyDdTWSr84E508fdI9jwIE9hhSAQ5AkCEASC7EmhL9qDZFKom3/XrRdz6iyq1d2bnUXshkFkc1L1wlAS8J4RZX1Tz1MStsJE1XMw2etblpBCyfqunbj1Usl/L9SkOHV/luIuQVbGHbl70tU83T0L3T3+YLSK9SzGUn0oBOkjNtoYIEjVMk9SHoJAkE8RWOlVT0IB3QwIAkEgiOAIBIEgEASCdBFYOZ1gDXIXE6ptI8NInJyrZ+puHDWWHa0VOWrjaLTepYIAM0wix+775H4qeUG0LzsSTYXRxD2zxAwqYnclJor8gX12BN6ZbChty1k+BD4HWGo/iNOezzliV+Hh9tvBeHkdCDIOctdQ3D0fKwMSIcg4O7mbO+FBtkPlYOK+GO7CUPAg44bJNRQ8yLgxGH4nCDIOUggyDsvT3AmCjBsKCDIOy9PcKQiSRVuqRrpRk6peyJZZYoOIQHWSJajnKXk7FsC9KyTLt8lvLkEiCjjLH6zGQEXl/kHIyuqeCpPMTpSEHcfEfZc8UI2pawuq3+/E0XPZeO9umFrJZDf16Iw2OnvSXYK47Xejed3njV7Aq7WXawvDI7vPFGriguIO+J6H7P2udhRCkC1iMyIIZuQnSJcaEKRPEzzIfAkYD1J8teNBaoAxxdrixRSrZkN2aTwIHuQBAaZYTLGOvkVYpHeQcr6TuKlx3DxJM6Yao7fcHjXC63IuJup5K9Oxuot0Fy83Pm1p4jgI4g7vth4EqWEJQTp44UFqRoQHKayv9tYgTLGegunmgKqZ8GNpPEgNOTwIHqRmMUW81M1HK3tuFLNqIwQpDvhowPAg2wFwowsgSPFd504nWIPUgGYNUlyD1OD9ufQMpWrGG8WZMkQdR+ZVz3LxmjGdcFOPZm1xPYjqm2sLU76kQ5DjbxQ3IBGC1KwMgnTwckGpQf9YenReLDzIFgH3heLaAh7EZUOnHgTZgjJa1ocgRYO9h4hd1iC1QWUN0sHLnVNDkJrxsUiv4TVlipWdbqSa9nVrLfYU965IN/kq+S32Gn+f/BadG50GNfaQf5k8T00nQunpXZHSM9tjrfod7Yg90b0r0otmB9zHXvWvBF5ZO9XYRTuydKAO/qpv0a9svFW/99KxZnjF2GQpXlW/0zS0e6EmGdAzPpi530GUMYyWNGcsxF2v6n4Erb2TbyutZhpuv2fYiR3NC0GOG8jqaScEOT42eyUhSAchR7HBg+yZ2tPf8SAdvGa8SWvD8liaKZaL3Jh6EASCXBCY8WJwU9yMMe/b7wJBIAgEETz6LAiipMJMAo6Ukr9PgFESsJItlTqh6ikl7o1I66lOmMrGPE6YymREZQyqXuCfpfVU0nekac1On3JTwzo+Qz1L2YLbb1XP7XfYXvfaW6jeQyYLNahK6RndN/eLsptAzQ1bd0jg1nGTNrgSsNtOmVlR3XS0EbnGMCN4bXTfIMjWkiBIh11nAgUP4r5Tx9Q7ky2oHuFBOujgQcaQQN0FguBBDqlYMwyFNcg4guNB8CDjrKlwpxkvBnc9OmWKlUnAKnJVRbyG7JqdFOVG+qqI3Thx6H2CjJK3Y2B7l+qbimpV9SIqOouMDik3O3VLRacWbPhJURXZnWGibEF9DlAStisBq35bkd17Mm/2QPersTtwSvabMdVwcXH7d5Z6al3m5MVS/XKlXDea1wo7cg0BgpzFpMe2A4Jc4QlB+gbm4jLWXNffDYJAkENWB0G2MDHFOmQ6PxdiilUA646K4kHwIIfMFQ+CB3lAIAxBRbVmUY4RXZtJk/FbJuWGVJjJq+GVMpkx6mURrzOMOXuTutGikaAgk2sVYxUmIYtnyQvUPWPcskQQTq4wVUfZgqtiKVtQmES/oz29K76tdK+9pA2O8c3YA6AGfMbebCcMRbVxRgI1t9+W3GnmK757W4AgfbOGIFtcnITeEKRjX3cPinhbHlrAdArhQbaguFOspbMJPAge5FMEnDWImyMNgnRs7y5AwYN03xpMsTqwsEh3J1VP6zHFuuMpVipxtdbUb5npKAk46igJ1TVHR5ZVz3L6raTckGMzmVdJuaFUZdL3PahYyhZCTcskfxXSrj4VBMaZ9K3kbTtpg2uwWT13T7pqx4xoXqffM7zEjAXpSpnXwTHqrLYTe8OU20EIchw5dwPQPXiQ4yg8LQlBigt4PMgWAQhSo5/lOZ1FeK1Zz/tmuKWt1bpMsaqI5eXxIHiQCwJMsbbGAEEgCAQRDudUBMmiZKP9Mc+tXrE5/m1SKXK1ZpGkIZM6uWbdqFbV72qfo7w7xQopNIsyVe1QsmUkq8hyCMf4RKKF3uVGdmfR25G0ITuyLto/OupbRYa8FsfxpQk8VoeaOIa3V8ddrJ4lIHGvf9nvatE5AxNnR+G9pP1JxwCCuOa5red6ELcFEMRFrlAPghTA2ikKQWovDXed4Yoa1khDEAu2biUIAkEOWdPqhA4z5tuHOnpVCIJAkEN2A0EOwXRzIdYgN0O4fwN3iqWk3JAQ4/feFZKsk7xA9STkzA/7Xd2UCCJnVyYBK9lSJShwkz0ovJRcqzCJnL6vko4rTDIVS433rAQeKq+yYQppQpCHrCZnyYXkdGxWndGbg9x2unlo1fPc6GcnLGnG9usZmKQcgCB9U4IgW1wgSMdWnI9D6u01g/3u21nVgyAQ5AEBPAge5OgLBg+CB7kggAfBg+BBxKsTgkCQZyFIbKjPNtUrSVNFfqppoopqVdG82Sb+kJOzKFkldypZXE1xVISz6purYqno7SzSV0nfChNlCyrCWSW5cOV0mbRhpczrLuDd+Bv3nHRnvq36NuPjqRtBYG09NXPzHl3fVMq5tqCeIZM2QJAx0wkIUjFzvywE6WDngoIH2YKJBym8EFfLvEyx/DfndU2mWOOwZIrVwdKZWrpDwhrERW5bz51NsAbpIMAUiynWEWoO9yDugtTN7u6GqKycb7tewu3bkYGvlnG8quq3u0fG3W1Y7e9ueXcNAkG2CECQLSYQpMOUM4U440F235FPCuBBrvDCg/QNaGWoCVOs2kJ8KV4QBIJ8igAeBA9yQWDleXzu95/aBOn20hAEgkAQwSMIMoggM6Q99f5Tsp/61uHuv87a4p7o6qbgVJjM6LfjVW/3W2vuYEUeuGsQCFKTeSHIGhK4L5S0HgSpDRwepIbXmUrjQTqjwRSrZqJMsViD1CzmqjQe5Cb4nrUyHgQPckHA9Zx4kI4HUWkcs1SUscc6Ulj2rtiznZ0q5L5CYk96/PWueFa2T9w1lPAU1b65mKi+xd7s7ESu2JP+PmnnG/PUKpV6NJOAfxL4u+Ot+q3uGfvjszS0kfI2O8EsG++HvFif8+US5Cy4uHsfrOnEjiE44Teubc3otxWXdxZDcIHcqwdB9hA6/jsEOY7V3ZSEIOOGCoKMw/I0d4Ig44YCgozD8jR3giDjhgKCjMPyNHeCIOOG4sUS5BsDQzfF44x6StobTZBIpZmdzqT65kqhSs1R/VbSd8jRXyZjnsqdZmZFhVekVc3S0Kp+q3pKylXSdypv78ViGdxZXmVlVKu773zG3mxXyrXkTpMgq7dfDz+3EYL0+Tz64CAIssV5RoYbCNKxZzxIzWnjQQp44UHwIJ8i4MRiuQGceJACUW8pigepoYcHKeCFB8GD4EEEYfYIkp68UyDhiKLqVCHlQSJSNiJDe1d2YlKUdRbpIT+GzNi7Qs7MftvrWybDz1CxQl7Nruw3NcUK7LMo7PBkWSS5knnjednpYHuxhdm3nOEnTI0w+so93KQN6hn3kMFDtX8GQSpj8rGsq9CpZ50qmtcxFAfIW+pAkC16EKSGibX22pti7bmsW4y+UheC1IxBYetGF2T3xINULHlSWQgCQY6YlqtoLj0f5EhHqmUgCAQ5YjMQpIOSOxd31l4zEubNWJAyxdoisHQNEvLdt8kouBG7MZd1ZL89mTdLeqAkTUfmdefiQbosmlRJwD+IJARqDCKqNcNEyfqZLB7y9veDbSHGNJO3lZ2ElJ5FCCvJP7UFd5HuRrWqN5sbeuC6VdWWlQSZIXcemY70yjihJu6z3Hp3cT4IBNkOr+tBIEiNKhCkg5e7SHclTTzIdhDUmq1m4reVhiAQ5IKAu4B3TZAp1hVyrEH6poQHwYM8IABBIMinCOBB8CCHZh+Z7LcXepPN0/deRFmj9p53qDOFQkr6zvqmopjVo5WEraRcFQWsnhcybyZvp/X2Bs6ZahTG40nRM8m8WR/c3XMzMHHv6dYbnfZHra9mLMQtwQaC1MwFgoyTtyFIzfYaHmQL2Iw3aXFYLsXxIB3kmGI9BQUPggd5ggAEgSAfEcCD4EF2Zx94EDwIHkTQRBEk8tBG3tveFf9/u0u/bYGQULNjw5TAEsezZcfSqWZkyRCiThbpqyK7I39wdhxf1MsSaigJ2I0Wfy1yEkfAa/dCxapZrRuQOCO4U7X8pe6RqY3mY+nhOwpnDPi9q1hqcGbgBUFcOmzrQZBBWOJBtkCeaZelO8wQxEXuqh4EgSAs0s1FOlOsNQrXoHfdITsnmreINh4ED3KIWUrSLNrcpXhstneO5HL3pKfSnsj9qgiipNxfiqPbIvlClrc3IlCz5BhKyg2J94MxEOlRZCKhhrsGUX37WkTeKrxUl9/tHJ83VOY1sL+pyowtt87ehxkfCmeodzeBXazsEsTdLenGpy1N+1PE8ObiEGQLofut4+bBuLoBBBmNqHE/CAJBPiKAB+kQCIJAEAgiPAsEgSAQBIJsEHBfDMYs1q7yotcgNmoLK7oyr2qikyxhtaEshPjhUaMxUe2fsc6wRI29aN7Vg+A8D4I4qNXrQJA6ZqeoAUHWDAMEWYPz8KdAkOGQdm8IQdbgPPwpEGQ4pBDkIwKsQfrGNfptqUJU3JCLNbR4fMpoTFikLxpBPMgaoF8kQf4HROjVDDxlJIwAAAAASUVORK5CYII=");

        return coupon;
    }

}
